logging:
  config: classpath:logback-spring.xml
  dir: /data/logs/leaf-jobs
  level:
    root: info
    com.leaf: debug
    org.springframework: info

spring:
  application:
  datasource:
    url: jdbc:mysql://cdb-r8rnnc1s.cd.tencentcdb.com:10038/leaf-jobs
    username: yefei
    password: yefei123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  quartz:
    job-store-type: jdbc
    scheduler-name: JOBS_QUARTZ_SCHEDULER

mybatis:
  mapper-locations: classpath:mappers/*.xml

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper

leaf:
  jobs:
    registerAddress: zookeeper.dev.xianglin.com:2181
    systemName: rjb